<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- <xacro:macro name="rrbot" params="parent prefix *origin"> -->

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.05" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.5" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="0.02" /> <!-- Space btw top of beam and the each joint -->

  <!-- <joint name="arm_joint" type="fixed">
    <parent link="chassis"/>
    <child link="arm_base_link"/>
    <origin xyz="-0.1 0 0"/>
  </joint> -->
  

  <!-- Base Link -->
  <link name="$arm_base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="arm_chassis_joint" type="fixed">
    <parent link="chassis"/>
    <child link="$arm_base_link" />
    <origin xyz="0.1 0 0"/>
  </joint>

  <joint name="$arm_joint1" type="continuous">
    <parent link="$arm_base_link"/>
    <child link="$arm_link1"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0"/>
  </joint>

  <!-- Middle Link -->
  <link name="$arm_link1">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="$arm_joint2" type="continuous">
    <parent link="$arm_link1"/>
    <child link="$arm_link2"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0"/>
  </joint>

  <!-- Top Link -->
  <link name="$arm_link2">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>



  <!-- </xacro:macro> -->

</robot>